server:
  port: 8084

  spring:
    datasource:

        url: jdbc:mysql://localhost:3306/spring-app?serverTimezone=UTC
        username: user
        password: user
        application:
          name: AppSpring
